(in-package :cotd)

(defconstant +item-card-blink+ 0)
(defconstant +item-card-teleport+ 1)
(defconstant +item-card-disguise+ 2)
(defconstant +item-card-sprint+ 3)
(defconstant +item-card-flying+ 4)
(defconstant +item-card-curse+ 5)
(defconstant +item-card-blindness+ 6)
(defconstant +item-card-fear+ 7)
(defconstant +item-card-slow+ 8)
(defconstant +item-card-silence+ 9)
(defconstant +item-card-confuse+ 10)
(defconstant +item-card-polymorph+ 11)

(defclass card-type ()
  ((id :initarg :id :accessor id)
   (name :initform "Unnamed card" :initarg :name :accessor name)
   (on-use :initform #'(lambda (card-type actor)
                         (declare (ignore card-type actor))
                         nil)
           :initarg :on-use :accessor on-use)
   ))

(defun get-card-type-by-id (card-type-id)
  (aref *card-types* card-type-id))

(defun set-card-type (card-type)
  (when (>= (id card-type) (length *card-types*))
    (adjust-array *card-types* (list (1+ (id card-type)))))
  (setf (aref *card-types* (id card-type)) card-type))
