(in-package :cotd)

(defparameter *game-events* (make-hash-table))

(defconstant +game-event-win-for-angels+ 0)
(defconstant +game-event-win-for-demons+ 1)
(defconstant +game-event-win-for-humans+ 2)
(defconstant +game-event-lose-game-died+ 3)
(defconstant +game-event-military-arrive+ 4)
(defconstant +game-event-snow-falls+ 5)
(defconstant +game-event-military-arrive-port-n+ 6)
(defconstant +game-event-military-arrive-port-s+ 7)
(defconstant +game-event-military-arrive-port-e+ 8)
(defconstant +game-event-military-arrive-port-w+ 9)
(defconstant +game-event-military-arrive-island+ 10)
(defconstant +game-event-lose-game-possessed+ 11)
(defconstant +game-event-adjust-outdoor-light+ 12)
(defconstant +game-event-win-for-thief+ 13)
(defconstant +game-event-rain-falls+ 14)
(defconstant +game-event-win-for-eater+ 15)
(defconstant +game-event-win-for-ghost+ 16)
(defconstant +game-event-unnatural-darkness+ 17)
(defconstant +game-event-constant-reanimation+ 18)

(defclass game-event ()
  ((id :initarg :id :accessor id)
   (disabled :initform nil :initarg :disabled :accessor disabled)
   (on-check :initarg :on-check :accessor on-check)
   (on-trigger :initarg :on-trigger :accessor on-trigger)))

(defun set-game-event (game-event)
  (setf (gethash (id game-event) *game-events*) game-event))

(defun get-game-event-by-id (game-event-id)
  (gethash game-event-id *game-events*))
