(in-package :cotd)

(defconstant +glyph-id-exclamation-mark+ 1)
(defconstant +glyph-id-hash+ 3)
(defconstant +glyph-id-large-a+ 33)
(defconstant +glyph-id-large-d+ 36)
(defconstant +glyph-id-large-m+ 45)
(defconstant +glyph-id-wall+ 96)
(defconstant +glyph-id-sacrificial-circle+ 124)
(defconstant +glyph-id-book+ 125)
(defconstant +glyph-id-christ-cross+ 127)
(defconstant +glyph-id-horizontal-river+ 131)
(defconstant +glyph-id-vertical-river+ 132)
(defconstant +glyph-id-three-dots+ 133)
(defconstant +glyph-id-crossed-swords+ 134)
(defconstant +glyph-id-church+ 135)
