(in-package :cotd)

(set-god-type (make-instance 'god :id +god-entity-malseraph+ :name "Malseraph"
                                  :piety-level-func #'(lambda (god piety-num)
                                                        (declare (ignore god))
                                                        (cond
                                                          ((<= piety-num +malseraphs-piety-very-low+) 0)
                                                          ((<= piety-num +malseraphs-piety-low+) 1)
                                                          ((<= piety-num +malseraphs-piety-medium+) 2)
                                                          ((<= piety-num +malseraphs-piety-high+) 3)
                                                          (t 4)))
                                  :piety-str-func #'(lambda (god piety-num)
                                                      (let ((piety-level (funcall (piety-level-func god) god piety-num)))
                                                        (cond
                                                          ((= piety-level 0) "Bored!")
                                                          ((= piety-level 1) "Losing interest")
                                                          ((= piety-level 2) "Interested")
                                                          ((= piety-level 3) "Intrigued")
                                                          (t "Amazed!"))))
                                  :piety-change-str-func #'(lambda (god piety-num-new piety-num-old)
                                                             (let ((piety-level (funcall (piety-level-func god) god piety-num-new))
                                                                   (piety-level-old (funcall (piety-level-func god) god piety-num-old)))
                                                               (cond
                                                                 ((= piety-level 0) "Malseraph is bored! ")
                                                                 ((and (= piety-level 1) (< piety-level piety-level-old)) "Malseraph loses interest in you. ")
                                                                 ((and (= piety-level 1) (> piety-level piety-level-old)) "Malseraph becomes slightly interested in you. ")
                                                                 ((and (= piety-level 2) (< piety-level piety-level-old)) "Malseraph's peak of interest is over. ")
                                                                 ((and (= piety-level 2) (> piety-level piety-level-old)) "Malseraph becomes mildly interested in you. ")
                                                                 ((and (= piety-level 3) (< piety-level piety-level-old)) "Malseraph wants you to continue. ")
                                                                 ((and (= piety-level 3) (> piety-level piety-level-old)) "Malseraph is intrigued. ")
                                                                 (t "Malseraph is amazed! "))))
                                  :piety-tick-func #'(lambda (god mob)
                                                       (declare (ignore god))
                                                       (set-mob-piety mob (- (get-worshiped-god-piety (worshiped-god mob))
                                                                             (+ 2 (random 3)))))))
