(in-package :cotd)

;;----------------------------------------
;; MISSION-DISTRICTS
;;----------------------------------------

(set-mission-district (make-instance 'mission-district :id +city-layout-normal+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-present+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-present+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-forest+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-present+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-present+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-port+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-present+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-present+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-island+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-present+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-present+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-river+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-present+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-present+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-barricaded-city+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-present+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-present+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-ruined-normal+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-absent+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-ruined-forest+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-absent+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-ruined-port+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-absent+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-ruined-island+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-absent+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-ruined-river+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-absent+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

;;----------------------------------------
;; MISSION-SCENARIOS
;;----------------------------------------

(set-mission-scenario (make-instance 'mission-scenario :id +mission-scenario-demon-attack+
                                                       :name "Demonic attack"
                                                       :district-layout-list (list +city-layout-normal+ +city-layout-forest+ +city-layout-port+ +city-layout-island+ +city-layout-river+ +city-layout-barricaded-city+)
                                                       :faction-list (list (list +faction-type-demons+ +mission-faction-attacker+)
                                                                           (list +faction-type-military+ +mission-faction-defender+)
                                                                           (list +faction-type-military+ +mission-faction-delayed+)
                                                                           (list +faction-type-angels+ +mission-faction-defender+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           )
                                                       :scenario-faction-list (list (list +specific-faction-type-player+ +sf-faction-demonic-attack-player+)
                                                                                    (list +specific-faction-type-dead-player+ +sf-faction-demonic-attack-dead-player+)
                                                                                    (list +specific-faction-type-angel-chrome+ +sf-faction-demonic-attack-angel-chrome+)
                                                                                    (list +specific-faction-type-angel-trinity+ +sf-faction-demonic-attack-angel-trinity+)
                                                                                    (list +specific-faction-type-demon-crimson+ +sf-faction-demonic-attack-demon-crimson+)
                                                                                    (list +specific-faction-type-demon-shadow+ +sf-faction-demonic-attack-demon-shadow+)
                                                                                    (list +specific-faction-type-demon-malseraph+ +sf-faction-demonic-attack-demon-malseraph+)
                                                                                    (list +specific-faction-type-military-chaplain+ +sf-faction-demonic-attack-military-chaplain+)
                                                                                    (list +specific-faction-type-military-scout+ +sf-faction-demonic-attack-military-scout+)
                                                                                    (list +specific-faction-type-priest+ +sf-faction-demonic-attack-priest+)
                                                                                    (list +specific-faction-type-satanist+ +sf-faction-demonic-attack-satanist+)
                                                                                    (list +specific-faction-type-eater+ +sf-faction-demonic-attack-eater+)
                                                                                    (list +specific-faction-type-thief+ +sf-faction-demonic-attack-thief+)
                                                                                    (list +specific-faction-type-ghost+ +sf-faction-demonic-attack-ghost+)
                                                                                    )
                                                       :objective-list (list (list +faction-type-demons+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-angels+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-military+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-church+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-satanists+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-eater+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-criminals+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-ghost+ (list +ai-package-patrol-district+))
                                                                             )
                                                       :win-condition-list (list (list +faction-type-demons+ +game-event-demon-attack-win-for-demons+)
                                                                                 (list +faction-type-angels+ +game-event-demon-attack-win-for-angels+)
                                                                                 (list +faction-type-military+ +game-event-demon-attack-win-for-military+)
                                                                                 (list +faction-type-church+ +game-event-demon-attack-win-for-church+)
                                                                                 (list +faction-type-satanists+ +game-event-demon-attack-win-for-satanists+)
                                                                                 (list +faction-type-eater+ +game-event-win-for-eater+)
                                                                                 (list +faction-type-criminals+ +game-event-win-for-thief+)
                                                                                 (list +faction-type-ghost+ +game-event-win-for-ghost+)
                                                                           )
                                     ))

(set-mission-scenario (make-instance 'mission-scenario :id +mission-scenario-demon-raid+
                                                       :name "Demonic raid"
                                                       :district-layout-list (list +city-layout-normal+ +city-layout-forest+ +city-layout-port+ +city-layout-island+ +city-layout-river+ +city-layout-barricaded-city+)
                                                       :faction-list (list (list +faction-type-demons+ +mission-faction-attacker+)
                                                                           (list +faction-type-military+ +mission-faction-defender+)
                                                                           (list +faction-type-military+ +mission-faction-delayed+)
                                                                           (list +faction-type-angels+ +mission-faction-defender+)
                                                                           (list +faction-type-angels+ +mission-faction-delayed+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           )
                                                       :scenario-faction-list (list (list +specific-faction-type-player+ +sf-faction-demonic-raid-player+)
                                                                                    (list +specific-faction-type-dead-player+ +sf-faction-demonic-raid-dead-player+)
                                                                                    (list +specific-faction-type-angel-chrome+ +sf-faction-demonic-raid-angel-chrome+)
                                                                                    (list +specific-faction-type-angel-trinity+ +sf-faction-demonic-raid-angel-trinity+)
                                                                                    (list +specific-faction-type-demon-crimson+ +sf-faction-demonic-raid-demon-crimson+)
                                                                                    (list +specific-faction-type-demon-shadow+ +sf-faction-demonic-raid-demon-shadow+)
                                                                                    (list +specific-faction-type-demon-malseraph+ +sf-faction-demonic-raid-demon-malseraph+)
                                                                                    (list +specific-faction-type-military-chaplain+ +sf-faction-demonic-raid-military-chaplain+)
                                                                                    (list +specific-faction-type-military-scout+ +sf-faction-demonic-raid-military-scout+)
                                                                                    (list +specific-faction-type-priest+ +sf-faction-demonic-raid-priest+)
                                                                                    (list +specific-faction-type-satanist+ +sf-faction-demonic-raid-satanist+)
                                                                                    (list +specific-faction-type-eater+ +sf-faction-demonic-raid-eater+)
                                                                                    (list +specific-faction-type-thief+ +sf-faction-demonic-raid-thief+)
                                                                                    (list +specific-faction-type-ghost+ +sf-faction-demonic-raid-ghost+)
                                                                                    )
                                                       :objective-list (list (list +faction-type-demons+ (list +ai-package-search-corpses+ +ai-package-pick-corpses+ +ai-package-return-corpses-to-portal+
                                                                                                               +ai-package-patrol-district+))
                                                                             (list +faction-type-angels+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-military+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-church+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-satanists+ (list +ai-package-search-corpses+ +ai-package-pick-corpses+ +ai-package-return-corpses-to-portal+
                                                                                                                  +ai-package-patrol-district+))
                                                                             (list +faction-type-eater+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-criminals+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-ghost+ (list +ai-package-patrol-district+))
                                                                             )
                                                       :win-condition-list (list (list +faction-type-demons+ +game-event-demon-raid-win-for-demons+)
                                                                                 (list +faction-type-angels+ +game-event-demon-raid-win-for-angels+)
                                                                                 (list +faction-type-military+ +game-event-demon-raid-win-for-military+)
                                                                                 (list +faction-type-church+ +game-event-demon-raid-win-for-church+)
                                                                                 (list +faction-type-satanists+ +game-event-demon-raid-win-for-satanists+)
                                                                                 (list +faction-type-eater+ +game-event-win-for-eater+)
                                                                                 (list +faction-type-criminals+ +game-event-win-for-thief+)
                                                                                 (list +faction-type-ghost+ +game-event-win-for-ghost+)
                                                                                 )
                                                       :post-sf-list (list +mission-sf-demonic-raid+)
                                                       :win-value-func #'(lambda ()
                                                                           (setf *demonic-raid-win-value* 200))
                                     ))

(set-mission-scenario (make-instance 'mission-scenario :id +mission-scenario-demon-steal+
                                                       :name "Demonic thievery"
                                                       :district-layout-list (list +city-layout-normal+ +city-layout-forest+ +city-layout-port+ +city-layout-island+ +city-layout-river+ +city-layout-barricaded-city+)
                                                       :faction-list (list (list +faction-type-demons+ +mission-faction-attacker+)
                                                                           (list +faction-type-military+ +mission-faction-defender+)
                                                                           (list +faction-type-military+ +mission-faction-delayed+)
                                                                           (list +faction-type-angels+ +mission-faction-defender+)
                                                                           (list +faction-type-angels+ +mission-faction-delayed+)
                                                                           )
                                                       :scenario-faction-list (list (list +specific-faction-type-player+ +sf-faction-demonic-steal-player+)
                                                                                    (list +specific-faction-type-dead-player+ +sf-faction-demonic-steal-dead-player+)
                                                                                    (list +specific-faction-type-angel-chrome+ +sf-faction-demonic-steal-angel-chrome+)
                                                                                    (list +specific-faction-type-angel-trinity+ +sf-faction-demonic-steal-angel-trinity+)
                                                                                    (list +specific-faction-type-demon-crimson+ +sf-faction-demonic-steal-demon-crimson+)
                                                                                    (list +specific-faction-type-demon-shadow+ +sf-faction-demonic-steal-demon-shadow+)
                                                                                    (list +specific-faction-type-demon-malseraph+ +sf-faction-demonic-steal-demon-malseraph+)
                                                                                    (list +specific-faction-type-military-chaplain+ +sf-faction-demonic-steal-military-chaplain+)
                                                                                    (list +specific-faction-type-military-scout+ +sf-faction-demonic-steal-military-scout+)
                                                                                    (list +specific-faction-type-priest+ +sf-faction-demonic-steal-priest+)
                                                                                    (list +specific-faction-type-satanist+ +sf-faction-demonic-steal-satanist+)
                                                                                    (list +specific-faction-type-eater+ +sf-faction-demonic-steal-eater+)
                                                                                    (list +specific-faction-type-thief+ +sf-faction-demonic-steal-thief+)
                                                                                    (list +specific-faction-type-ghost+ +sf-faction-demonic-steal-ghost+)
                                                                                    )
                                                       :objective-list (list (list +faction-type-demons+ (list +ai-package-search-relic+ +ai-package-pick-relic+ +ai-package-return-relic-to-portal+ +ai-package-patrol-district+))
                                                                             (list +faction-type-angels+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-military+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-church+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-satanists+ (list +ai-package-search-relic+ +ai-package-pick-relic+ +ai-package-return-relic-to-portal+ +ai-package-patrol-district+))
                                                                             (list +faction-type-eater+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-criminals+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-ghost+ (list +ai-package-patrol-district+))
                                                                             )
                                                       :win-condition-list (list (list +faction-type-demons+ +game-event-demon-steal-win-for-demons+)
                                                                                 (list +faction-type-angels+ +game-event-demon-steal-win-for-angels+)
                                                                                 (list +faction-type-military+ +game-event-demon-steal-win-for-military+)
                                                                                 (list +faction-type-church+ +game-event-demon-steal-win-for-church+)
                                                                                 (list +faction-type-satanists+ +game-event-demon-steal-win-for-satanists+)
                                                                                 (list +faction-type-eater+ +game-event-win-for-eater+)
                                                                                 (list +faction-type-criminals+ +game-event-win-for-thief+)
                                                                                 (list +faction-type-ghost+ +game-event-win-for-ghost+)
                                                                                 )
                                                       :post-sf-list (list +mission-sf-demonic-steal+)
                                     ))

(set-mission-scenario (make-instance 'mission-scenario :id +mission-scenario-demon-conquest+
                                                       :name "Demonic conquest"
                                                       :district-layout-list (list +city-layout-normal+ +city-layout-forest+ +city-layout-port+ +city-layout-island+ +city-layout-river+ +city-layout-barricaded-city+)
                                                       :faction-list (list (list +faction-type-demons+ +mission-faction-attacker+)
                                                                           (list +faction-type-military+ +mission-faction-defender+)
                                                                           (list +faction-type-military+ +mission-faction-delayed+)
                                                                           (list +faction-type-angels+ +mission-faction-defender+)
                                                                           (list +faction-type-angels+ +mission-faction-delayed+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           )
                                                       :scenario-faction-list (list (list +specific-faction-type-player+ +sf-faction-demonic-conquest-player+)
                                                                                    (list +specific-faction-type-dead-player+ +sf-faction-demonic-conquest-dead-player+)
                                                                                    (list +specific-faction-type-angel-chrome+ +sf-faction-demonic-conquest-angel-chrome+)
                                                                                    (list +specific-faction-type-angel-trinity+ +sf-faction-demonic-conquest-angel-trinity+)
                                                                                    (list +specific-faction-type-demon-crimson+ +sf-faction-demonic-conquest-demon-crimson+)
                                                                                    (list +specific-faction-type-demon-shadow+ +sf-faction-demonic-conquest-demon-shadow+)
                                                                                    (list +specific-faction-type-demon-malseraph+ +sf-faction-demonic-conquest-demon-malseraph+)
                                                                                    (list +specific-faction-type-military-chaplain+ +sf-faction-demonic-conquest-military-chaplain+)
                                                                                    (list +specific-faction-type-military-scout+ +sf-faction-demonic-conquest-military-scout+)
                                                                                    (list +specific-faction-type-priest+ +sf-faction-demonic-conquest-priest+)
                                                                                    (list +specific-faction-type-satanist+ +sf-faction-demonic-conquest-satanist+)
                                                                                    (list +specific-faction-type-eater+ +sf-faction-demonic-conquest-eater+)
                                                                                    (list +specific-faction-type-thief+ +sf-faction-demonic-conquest-thief+)
                                                                                    (list +specific-faction-type-ghost+ +sf-faction-demonic-conquest-ghost+)
                                                                                    )
                                                       :objective-list (list (list +faction-type-demons+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-angels+ (list +ai-package-patrol-district+ +ai-package-find-sigil+))
                                                                             (list +faction-type-military+ (list +ai-package-patrol-district+ +ai-package-find-sigil+))
                                                                             (list +faction-type-church+ (list +ai-package-patrol-district+ +ai-package-find-sigil+))
                                                                             (list +faction-type-satanists+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-eater+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-criminals+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-ghost+ (list +ai-package-patrol-district+))
                                                                             )
                                                       :win-condition-list (list (list +faction-type-demons+ +game-event-demon-conquest-win-for-demons+)
                                                                                 (list +faction-type-angels+ +game-event-demon-conquest-win-for-angels+)
                                                                                 (list +faction-type-military+ +game-event-demon-conquest-win-for-military+)
                                                                                 (list +faction-type-church+ +game-event-demon-conquest-win-for-church+)
                                                                                 (list +faction-type-satanists+ +game-event-demon-conquest-win-for-satanists+)
                                                                                 (list +faction-type-eater+ +game-event-win-for-eater+)
                                                                                 (list +faction-type-criminals+ +game-event-win-for-thief+)
                                                                                 (list +faction-type-ghost+ +game-event-win-for-ghost+)
                                                                                 )
                                                       :post-sf-list (list +mission-sf-demonic-steal+)
                                                       ))

(set-mission-scenario (make-instance 'mission-scenario :id +mission-scenario-demon-raid-ruined+
                                                       :name "Demonic raid"
                                                       :district-layout-list (list +city-layout-ruined-normal+ +city-layout-ruined-forest+ +city-layout-ruined-port+ +city-layout-ruined-island+ +city-layout-ruined-river+)
                                                       :faction-list (list (list +faction-type-demons+ +mission-faction-attacker+)
                                                                           (list +faction-type-military+ +mission-faction-defender+)
                                                                           (list +faction-type-angels+ +mission-faction-defender+)
                                                                           (list +faction-type-angels+ +mission-faction-delayed+)
                                                                           )
                                                       :scenario-faction-list (list (list +specific-faction-type-player+ +sf-faction-demonic-raid-ruined-player+)
                                                                                    (list +specific-faction-type-dead-player+ +sf-faction-demonic-raid-ruined-dead-player+)
                                                                                    (list +specific-faction-type-angel-chrome+ +sf-faction-demonic-raid-ruined-angel-chrome+)
                                                                                    (list +specific-faction-type-angel-trinity+ +sf-faction-demonic-raid-ruined-angel-trinity+)
                                                                                    (list +specific-faction-type-demon-crimson+ +sf-faction-demonic-raid-ruined-demon-crimson+)
                                                                                    (list +specific-faction-type-demon-shadow+ +sf-faction-demonic-raid-ruined-demon-shadow+)
                                                                                    (list +specific-faction-type-demon-malseraph+ +sf-faction-demonic-raid-ruined-demon-malseraph+)
                                                                                    (list +specific-faction-type-military-chaplain+ +sf-faction-demonic-raid-ruined-military-chaplain+)
                                                                                    (list +specific-faction-type-military-scout+ +sf-faction-demonic-raid-ruined-military-scout+)
                                                                                    (list +specific-faction-type-eater+ +sf-faction-demonic-raid-eater+)
                                                                                    )
                                                       :objective-list (list (list +faction-type-demons+ (list +ai-package-search-corpses+ +ai-package-pick-corpses+ +ai-package-return-corpses-to-portal+
                                                                                                               +ai-package-patrol-district+))
                                                                             (list +faction-type-angels+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-military+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-eater+ (list +ai-package-patrol-district+))
                                                                             )
                                                       :win-condition-list (list (list +faction-type-demons+ +game-event-demon-raid-win-for-demons+)
                                                                                 (list +faction-type-angels+ +game-event-demon-raid-win-for-angels+)
                                                                                 (list +faction-type-military+ +game-event-demon-raid-win-for-military+)
                                                                                 (list +faction-type-eater+ +game-event-win-for-eater+)
                                                                                 )
                                                       :post-sf-list (list +mission-sf-demonic-raid+
                                                                           +mission-sf-ruined-district+)
                                                       :win-value-func #'(lambda ()
                                                                           (setf *demonic-raid-win-value* 100))
                                     ))

(set-mission-scenario (make-instance 'mission-scenario :id +mission-scenario-demon-conquest-ruined+
                                                       :name "Demonic conquest"
                                                       :district-layout-list (list +city-layout-ruined-normal+ +city-layout-ruined-forest+ +city-layout-ruined-port+ +city-layout-ruined-island+ +city-layout-ruined-river+)
                                                       :faction-list (list (list +faction-type-demons+ +mission-faction-attacker+)
                                                                           (list +faction-type-military+ +mission-faction-defender+)
                                                                           (list +faction-type-military+ +mission-faction-delayed+)
                                                                           (list +faction-type-military+ +mission-faction-absent+)
                                                                           (list +faction-type-angels+ +mission-faction-defender+)
                                                                           (list +faction-type-angels+ +mission-faction-delayed+)
                                                                           )
                                                       :scenario-faction-list (list (list +specific-faction-type-player+ +sf-faction-demonic-conquest-ruined-player+)
                                                                                    (list +specific-faction-type-dead-player+ +sf-faction-demonic-conquest-ruined-dead-player+)
                                                                                    (list +specific-faction-type-angel-chrome+ +sf-faction-demonic-conquest-ruined-angel-chrome+)
                                                                                    (list +specific-faction-type-angel-trinity+ +sf-faction-demonic-conquest-ruined-angel-trinity+)
                                                                                    (list +specific-faction-type-demon-crimson+ +sf-faction-demonic-conquest-ruined-demon-crimson+)
                                                                                    (list +specific-faction-type-demon-shadow+ +sf-faction-demonic-conquest-ruined-demon-shadow+)
                                                                                    (list +specific-faction-type-demon-malseraph+ +sf-faction-demonic-conquest-ruined-demon-malseraph+)
                                                                                    (list +specific-faction-type-military-chaplain+ +sf-faction-demonic-conquest-ruined-military-chaplain+)
                                                                                    (list +specific-faction-type-military-scout+ +sf-faction-demonic-conquest-ruined-military-scout+)
                                                                                    (list +specific-faction-type-eater+ +sf-faction-demonic-conquest-ruined-eater+)
                                                                                    )
                                                       :objective-list (list (list +faction-type-demons+ (list +ai-package-patrol-district+))
                                                                             (list +faction-type-angels+ (list +ai-package-patrol-district+ +ai-package-find-sigil+))
                                                                             (list +faction-type-military+ (list +ai-package-patrol-district+ +ai-package-find-sigil+))
                                                                             (list +faction-type-eater+ (list +ai-package-patrol-district+))
                                                                             )
                                                       :win-condition-list (list (list +faction-type-demons+ +game-event-demon-conquest-win-for-demons+)
                                                                                 (list +faction-type-angels+ +game-event-demon-conquest-win-for-angels+)
                                                                                 (list +faction-type-military+ +game-event-demon-conquest-win-for-military+)
                                                                                 (list +faction-type-eater+ +game-event-win-for-eater+)
                                                                                 )
                                                       :post-sf-list (list +mission-sf-demonic-steal+
                                                                           +mission-sf-ruined-district+)
                                                       ))
