(in-package :cotd)

;;----------------------------------------
;; MISSION-DISTRICTS
;;----------------------------------------

(set-mission-district (make-instance 'mission-district :id +city-layout-normal+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           (list +faction-type-satanists+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-present+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-present+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-forest+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           (list +faction-type-satanists+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-present+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-present+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-port+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           (list +faction-type-satanists+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-present+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-present+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-island+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           (list +faction-type-satanists+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-present+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-present+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-river+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           (list +faction-type-satanists+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-present+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-present+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

(set-mission-district (make-instance 'mission-district :id +city-layout-barricaded-city+
                                                       :faction-list (list (list +faction-type-civilians+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-present+)
                                                                           (list +faction-type-church+ +mission-faction-absent+)
                                                                           (list +faction-type-satanists+ +mission-faction-present+)
                                                                           (list +faction-type-satanists+ +mission-faction-absent+)
                                                                           (list +faction-type-eater+ +mission-faction-present+)
                                                                           (list +faction-type-eater+ +mission-faction-absent+)
                                                                           (list +faction-type-criminals+ +mission-faction-present+)
                                                                           (list +faction-type-criminals+ +mission-faction-absent+)
                                                                           (list +faction-type-ghost+ +mission-faction-present+)
                                                                           (list +faction-type-ghost+ +mission-faction-absent+))))

;;----------------------------------------
;; MISSION-SCENARIOS
;;----------------------------------------

(set-mission-scenario (make-instance 'mission-scenario :id +mission-scenario-demon-attack+
                                                       :name "Demonic attack"
                                                       :district-layout-list (list +city-layout-normal+ +city-layout-forest+ +city-layout-port+ +city-layout-island+ +city-layout-river+ +city-layout-barricaded-city+)
                                                       :faction-list (list (list +faction-type-demons+ +mission-faction-attacker+)
                                                                           (list +faction-type-military+ +mission-faction-defender+)
                                                                           (list +faction-type-military+ +mission-faction-delayed+)
                                                                           (list +faction-type-angels+ +mission-faction-defender+)
                                                                           (list +faction-type-church+ +mission-faction-defender+)
                                                                           (list +faction-type-satanists+ +mission-faction-attacker+)
                                                                           (list +faction-type-eater+ +mission-faction-attacker+)
                                                                           (list +faction-type-criminals+ +mission-faction-defender+)
                                                                           (list +faction-type-ghost+ +mission-faction-defender+)
                                                                           )
                                                       :scenario-faction-list (list (list +specific-faction-type-player+ +sf-faction-demonic-attack-player+)
                                                                                    (list +specific-faction-type-dead-player+ +sf-faction-demonic-attack-dead-player+)
                                                                                    (list +specific-faction-type-angel-chrome+ +sf-faction-demonic-attack-angel-chrome+)
                                                                                    (list +specific-faction-type-angel-trinity+ +sf-faction-demonic-attack-angel-trinity+)
                                                                                    (list +specific-faction-type-demon-crimson+ +sf-faction-demonic-attack-demon-crimson+)
                                                                                    (list +specific-faction-type-demon-shadow+ +sf-faction-demonic-attack-demon-shadow+)
                                                                                    (list +specific-faction-type-demon-malseraph+ +sf-faction-demonic-attack-demon-malseraph+)
                                                                                    (list +specific-faction-type-military-chaplain+ +sf-faction-demonic-attack-military-chaplain+)
                                                                                    (list +specific-faction-type-military-scout+ +sf-faction-demonic-attack-military-scout+)
                                                                                    (list +specific-faction-type-priest+ +sf-faction-demonic-attack-priest+)
                                                                                    (list +specific-faction-type-satanist+ +sf-faction-demonic-attack-satanist+)
                                                                                    (list +specific-faction-type-eater+ +sf-faction-demonic-attack-eater+)
                                                                                    (list +specific-faction-type-thief+ +sf-faction-demonic-attack-thief+)
                                                                                    (list +specific-faction-type-ghost+ +sf-faction-demonic-attack-ghost+)
                                                                                    )
                                                       :objective-list (list (list +faction-type-demons+ +ai-package-patrol-district+)
                                                                             (list +faction-type-angels+ +ai-package-patrol-district+)
                                                                             (list +faction-type-military+ +ai-package-patrol-district+)
                                                                             (list +faction-type-church+ +ai-package-patrol-district+)
                                                                             (list +faction-type-satanists+ +ai-package-patrol-district+)
                                                                             (list +faction-type-eater+ +ai-package-patrol-district+)
                                                                             (list +faction-type-criminals+ +ai-package-patrol-district+)
                                                                             (list +faction-type-ghost+ +ai-package-patrol-district+)
                                                                             )
                                                       :win-condition-list (list (list +faction-type-demons+ +game-event-demon-attack-win-for-demons+)
                                                                                 (list +faction-type-angels+ +game-event-demon-attack-win-for-angels+)
                                                                                 (list +faction-type-military+ +game-event-demon-attack-win-for-military+)
                                                                                 (list +faction-type-church+ +game-event-demon-attack-win-for-church+)
                                                                                 (list +faction-type-satanists+ +game-event-demon-attack-win-for-satanists+)
                                                                                 (list +faction-type-eater+ +game-event-win-for-eater+)
                                                                                 (list +faction-type-criminals+ +game-event-win-for-thief+)
                                                                                 (list +faction-type-ghost+ +game-event-win-for-ghost+)
                                                                           )
                                     ))

(set-mission-scenario (make-instance 'mission-scenario :id +mission-scenario-demon-raid+
                                                       :name "Demonic raid"
                                                       :district-layout-list (list +city-layout-normal+ +city-layout-forest+ +city-layout-port+ +city-layout-island+ +city-layout-river+ +city-layout-barricaded-city+)
                                                       :faction-list (list (list +faction-type-demons+ +mission-faction-attacker+)
                                                                           (list +faction-type-military+ +mission-faction-defender+)
                                                                           (list +faction-type-military+ +mission-faction-delayed+)
                                                                           (list +faction-type-angels+ +mission-faction-defender+)
                                                                           (list +faction-type-angels+ +mission-faction-delayed+)
                                                                           (list +faction-type-church+ +mission-faction-defender+)
                                                                           (list +faction-type-satanists+ +mission-faction-attacker+)
                                                                           (list +faction-type-eater+ +mission-faction-attacker+)
                                                                           (list +faction-type-criminals+ +mission-faction-defender+)
                                                                           (list +faction-type-ghost+ +mission-faction-defender+)
                                                                           )
                                                       :scenario-faction-list (list (list +specific-faction-type-player+ +sf-faction-demonic-raid-player+)
                                                                                    (list +specific-faction-type-dead-player+ +sf-faction-demonic-raid-dead-player+)
                                                                                    (list +specific-faction-type-angel-chrome+ +sf-faction-demonic-raid-angel-chrome+)
                                                                                    (list +specific-faction-type-angel-trinity+ +sf-faction-demonic-raid-angel-trinity+)
                                                                                    (list +specific-faction-type-demon-crimson+ +sf-faction-demonic-raid-demon-crimson+)
                                                                                    (list +specific-faction-type-demon-shadow+ +sf-faction-demonic-raid-demon-shadow+)
                                                                                    (list +specific-faction-type-demon-malseraph+ +sf-faction-demonic-raid-demon-malseraph+)
                                                                                    (list +specific-faction-type-military-chaplain+ +sf-faction-demonic-raid-military-chaplain+)
                                                                                    (list +specific-faction-type-military-scout+ +sf-faction-demonic-raid-military-scout+)
                                                                                    (list +specific-faction-type-priest+ +sf-faction-demonic-raid-priest+)
                                                                                    (list +specific-faction-type-satanist+ +sf-faction-demonic-raid-satanist+)
                                                                                    (list +specific-faction-type-eater+ +sf-faction-demonic-raid-eater+)
                                                                                    (list +specific-faction-type-thief+ +sf-faction-demonic-raid-thief+)
                                                                                    (list +specific-faction-type-ghost+ +sf-faction-demonic-raid-ghost+)
                                                                                    )
                                                       :objective-list (list (list +faction-type-demons+ +ai-package-patrol-district+)
                                                                             (list +faction-type-angels+ +ai-package-patrol-district+)
                                                                             (list +faction-type-military+ +ai-package-patrol-district+)
                                                                             (list +faction-type-church+ +ai-package-patrol-district+)
                                                                             (list +faction-type-satanists+ +ai-package-patrol-district+)
                                                                             (list +faction-type-eater+ +ai-package-patrol-district+)
                                                                             (list +faction-type-criminals+ +ai-package-patrol-district+)
                                                                             (list +faction-type-ghost+ +ai-package-patrol-district+)
                                                                             )
                                                       :win-condition-list (list (list +faction-type-demons+ +game-event-demon-attack-win-for-demons+)
                                                                                 (list +faction-type-angels+ +game-event-demon-attack-win-for-angels+)
                                                                                 (list +faction-type-military+ +game-event-demon-attack-win-for-military+)
                                                                                 (list +faction-type-church+ +game-event-demon-attack-win-for-church+)
                                                                                 (list +faction-type-satanists+ +game-event-demon-attack-win-for-satanists+)
                                                                                 (list +faction-type-eater+ +game-event-win-for-eater+)
                                                                                 (list +faction-type-criminals+ +game-event-win-for-thief+)
                                                                                 (list +faction-type-ghost+ +game-event-win-for-ghost+)
                                                                                 )
                                                       :post-sf-id +mission-sf-demonic-raid+
                                                       ))
