(in-package :cotd)

(set-game-event (make-instance 'game-event :id +game-event-win-for-angels+ :disabled nil
                                           :on-check #'(lambda (world)
                                                         (if (or (zerop (total-demons world))
                                                                 (and (mob-ability-p *player* +mob-abil-angel+)
                                                                      (= (mob-type *player*) +mob-type-archangel+)
                                                                      (>= (cur-fp *player*) (max-fp *player*))))
                                                           t
                                                           nil))
                                           :on-trigger #'(lambda (world)
                                                           (declare (ignore world))
                                                           (add-message (format nil "~%"))
                                                           (add-message (format nil "Congratulations! You have won the game!~%"))
                                                           (setf *current-window* (make-instance 'cell-window))
                                                           (make-output *current-window*)
                                                           (sdl:with-events ()
                                                             (:quit-event () (funcall (quit-func *current-window*)) t)
                                                             (:key-down-event () 
                                                                              (setf *current-window* (make-instance 'final-stats-window :game-over-type +game-over-angels-won+))
                                                                              (make-output *current-window*)
                                                                              (run-window *current-window*))
                                                             (:video-expose-event () (make-output *current-window*))))))

(set-game-event (make-instance 'game-event :id +game-event-win-for-demons+ :disabled nil
                                           :on-check #'(lambda (world)
                                                         (if (or (zerop (total-angels world))
                                                                 (and (mob-ability-p *player* +mob-abil-demon+)
                                                                      (= (mob-type *player*) +mob-type-archdemon+)
                                                                      (>= (cur-fp *player*) (max-fp *player*))))
                                                           t
                                                           nil))
                                           :on-trigger #'(lambda (world)
                                                           (declare (ignore world))
                                                           (add-message (format nil "~%"))
                                                           (add-message (format nil "Congratulations! You have won the game!~%"))
                                                           (setf *current-window* (make-instance 'cell-window))
                                                           (make-output *current-window*)
                                                           (sdl:with-events ()
                                                             (:quit-event () (funcall (quit-func *current-window*)) t)
                                                             (:key-down-event () 
                                                                              (setf *current-window* (make-instance 'final-stats-window :game-over-type +game-over-demons-won+))
                                                                              (make-output *current-window*)
                                                                              (run-window *current-window*))
                                                             (:video-expose-event () (make-output *current-window*))))))

(set-game-event (make-instance 'game-event :id +game-event-win-for-humans+ :disabled nil
                                           :on-check #'(lambda (world)
                                                         (if (zerop (total-demons world))
                                                           t
                                                           nil))
                                           :on-trigger #'(lambda (world)
                                                           (declare (ignore world))
                                                           (add-message (format nil "~%"))
                                                           (add-message (format nil "Congratulations! You have won the game!~%"))
                                                           (setf *current-window* (make-instance 'cell-window))
                                                           (make-output *current-window*)
                                                           (sdl:with-events ()
                                                             (:quit-event () (funcall (quit-func *current-window*)) t)
                                                             (:key-down-event () 
                                                                              (setf *current-window* (make-instance 'final-stats-window :game-over-type +game-over-angels-won+))
                                                                              (make-output *current-window*)
                                                                              (run-window *current-window*))
                                                             (:video-expose-event () (make-output *current-window*))))))

(set-game-event (make-instance 'game-event :id +game-event-lose-game+ :disabled nil
                                           :on-check #'(lambda (world)
                                                         (declare (ignore world))
                                                         (if (check-dead *player*)
                                                           t
                                                           nil))
                                           :on-trigger #'(lambda (world)
                                                           (declare (ignore world))
                                                           (add-message (create-string "~%"))
                                                           (add-message (create-string "You are dead.~%"))
                                                           (setf *current-window* (make-instance 'cell-window))
                                                           (update-visible-area (level *world*) (x *player*) (y *player*))
                                                           (make-output *current-window*)
                                                           (sdl:with-events ()
                                                             (:quit-event () (funcall (quit-func *current-window*)) t)
                                                             (:key-down-event () 
                                                                              (setf *current-window* (make-instance 'final-stats-window :game-over-type +game-over-player-dead+))
                                                                              (make-output *current-window*)
                                                                              (run-window *current-window*))
                                                             (:video-expose-event () (make-output *current-window*))))))
