(in-package :cotd)

(defconstant +world-sector-normal-residential+ 0)
(defconstant +world-sector-normal-sea+ 1)
(defconstant +world-sector-normal-island+ 2)
(defconstant +world-sector-normal-port+ 3)
(defconstant +world-sector-normal-lake+ 4)
(defconstant +world-sector-normal-forest+ 5)

(defconstant +world-sector-abandoned-residential+ 6)
(defconstant +world-sector-abandoned-island+ 7)
(defconstant +world-sector-abandoned-port+ 8)
(defconstant +world-sector-abandoned-lake+ 9)
(defconstant +world-sector-abandoned-forest+ 10)

(defconstant +world-sector-corrupted-residential+ 11)
(defconstant +world-sector-corrupted-island+ 12)
(defconstant +world-sector-corrupted-port+ 13)
(defconstant +world-sector-corrupted-lake+ 14)
(defconstant +world-sector-corrupted-forest+ 15)
